FROM {{jenkins_image}}:{{jenkins_image_tag}}

USER root

RUN set -x \
	&& curl -fSL "https://download.docker.com/linux/static/stable/x86_64/docker-{{docker_version.stdout}}.tgz" -o docker.tgz \
	&& tar -xzvf docker.tgz \
	&& mv docker/* /usr/local/bin/ \
	&& rmdir docker \
	&& rm docker.tgz \
	&& docker -v \
        && apt-get update \
        && apt-get install -y sudo \
        && curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose \
        && chmod a+x /usr/local/bin/docker-compose \
        && rm -rf /var/lib/apt/lists/*

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

RUN groupadd -for -g {{docker_gid.stdout}} docker \
             && usermod -aG docker jenkins

USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
