- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install base packages
  apt:
    name: "{{item}}"
  with_items:
    - python-mysqldb
    - python-pip

- command: 'pip install --upgrade pip'

- name: install python module for ansible
  pip:
    name: "{{item}}"
  with_items:
    - docker-py
